#!/bin/sh

git clone --depth=1 https://github.com/TokTok/toxcore

RUN $CMAKE -Btoxcore/$BUILD_DIR -Htoxcore -DBOOTSTRAP_DAEMON=OFF -DASSOC_DHT=ON -DDEBUG=ON -DSTRICT_ABI=ON -DCMAKE_INSTALL_PREFIX:PATH=$CURDIR/libs
RUN $MAKE -C toxcore/$BUILD_DIR -j$NPROC -k install

rm -rf toxcore
