#!/bin/sh

# toxcore
git clone --depth=1 https://github.com/irungentoo/toxcore
cd toxcore
autoreconf -if
./configure
make -j$(nproc) > /dev/null
sudo make install
echo '/usr/local/lib/' | sudo tee -a /etc/ld.so.conf.d/locallib.conf
sudo ldconfig
cd ..

rm -rf toxcore
