#!/bin/sh

set -e -x

sudo add-apt-repository -y ppa:mc3man/trusty-media
sudo add-apt-repository -y ppa:chris-lea/libsodium

sudo apt-get update -qq

sudo apt-get install -y --force-yes \
  ffmpeg \
  libgtk2.0-dev \
  libopenal-dev \
  libopus-dev \
  libqrencode-dev \
  libqt5svg5-dev \
  libsodium-dev \
  libsqlcipher-dev \
  libswscale-dev \
  libvpx-dev \
  qttools5-dev \
  qttools5-dev-tools \
  \
  libasound-dev \
  libass-dev \
  libfdk-aac-dev \
  libmp3lame-dev \
  libogg-dev \
  libopencore-amrnb-dev \
  libopencore-amrwb-dev \
  libsdl1.2-dev \
  libsdl2-dev \
  libsoxr-dev \
  libspeex-dev \
  libva-dev \
  libvdpau-dev \
  libvidstab-dev \
  libvorbis-dev \
  libx264-dev \
  libx265-dev \
  libxv-dev \
  libxvidcore-dev \
  libwavpack-dev
