#!/bin/sh

GENERATED='.*/_build/.*'

coveralls                        \
  --exclude test                 \
  --exclude updater              \
  --exclude-pattern "$GENERATED" \
  --gcov-options '\-lp'
