name: 'Load docker image'
inputs:
  docker_image_name:
    description: "Name of docker image"
    required: True
runs:
  using: 'composite'
  steps:
    - uses: docker/setup-buildx-action@master
    - name: Setup buildx cache
      uses: actions/cache@v2
      with:
        path: |
          /tmp/.buildx-cache
        key: ${{ runner.os }}-${{ inputs.docker_image_name }}-${{ github.sha }}
    - name: Load cached docker images
      shell: bash
      run: docker buildx bake --set *.cache-from=type=local,src=/tmp/.buildx-cache  -f docker-compose.yml ${{ inputs.docker_image_name }} --load
