#ifndef COREDEFINES_H
#define COREDEFINES_H

#define TOXAV_MAX_CALLS 16
#define GROUPCHAT_MAX_SIZE 32
#define TOX_FILE_INTERVAL 1
#define TOXAV_RINGING_TIME 45

// TODO: Put that in the settings
#define TOXAV_MAX_VIDEO_WIDTH 1280
#define TOXAV_MAX_VIDEO_HEIGHT 720

#endif // COREDEFINES_H
