brew "coreutils"
brew "git"
brew "libtool"
brew "cmake"
brew "pkgconfig"
brew "check"
brew "libvpx"
brew "opus"
brew "libsodium"
brew "ffmpeg"
brew "libexif"
brew "qrencode"
brew "qt@5"
brew "sqlcipher"
brew "openal-soft"
brew "msgpack"
# accelerate builds with ccache
brew "ccache"

# brew install  #kf5-sonnet

# needed for kf5-sonnet
# brew tap kde-mac/kde https://invent.kde.org/packaging/homebrew-kde.git
# brew "kf5-sonnet"
